# Alembic Configuration File

[alembic]

# Path menuju direktori script migrasi Alembic
script_location = backend/src/database/migration

# Template penamaan file migrasi di folder versions/
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s

# Path direktori python
prepend_sys_path = backend

# URL Database default (akan di-override oleh settings.py di env.py)
sqlalchemy.url = postgresql+asyncpg://postgres:supersecret_password@localhost:5432/cryptobot

# Logging settings

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S