"""optimize indexes and constraints

Revision ID: 1e44724e9b78
Revises: '3113533826e3'
Create Date: 2026-08-14 21:57:38.082305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e44724e9b78'
down_revision: Union[str, None] = '3113533826e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bot_logs_level_created', 'bot_logs', ['level', 'created_at'], unique=False)
    op.create_index('idx_executions_trade_time', 'executions', ['trade_id', 'executed_at'], unique=False)
    op.create_index('idx_orders_purpose_status', 'orders', ['purpose', 'status'], unique=False)
    op.create_index('idx_orders_trade_status', 'orders', ['trade_id', 'status'], unique=False)
    op.create_index('idx_trade_events_trade_time', 'trade_events', ['trade_id', 'created_at'], unique=False)
    op.create_index('idx_trades_account_status', 'trades', ['account_id', 'status'], unique=False)
    op.create_index('idx_trades_instrument_status', 'trades', ['instrument_id', 'status'], unique=False)
    op.create_index('idx_trades_status_created_at', 'trades', ['status', 'created_at'], unique=False)
    op.create_index('idx_signals_status_created', 'trading_signals', ['status', 'created_at'], unique=False)
    op.create_index('idx_signals_tg_msg_id', 'trading_signals', ['telegram_message_id'], unique=False)
    op.create_unique_constraint('uk_watchlist_instrument_id', 'watchlist', ['instrument_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_watchlist_instrument_id', 'watchlist', type_='unique')
    op.drop_index('idx_signals_tg_msg_id', table_name='trading_signals')
    op.drop_index('idx_signals_status_created', table_name='trading_signals')
    op.drop_index('idx_trades_status_created_at', table_name='trades')
    op.drop_index('idx_trades_instrument_status', table_name='trades')
    op.drop_index('idx_trades_account_status', table_name='trades')
    op.drop_index('idx_trade_events_trade_time', table_name='trade_events')
    op.drop_index('idx_orders_trade_status', table_name='orders')
    op.drop_index('idx_orders_purpose_status', table_name='orders')
    op.drop_index('idx_executions_trade_time', table_name='executions')
    op.drop_index('idx_bot_logs_level_created', table_name='bot_logs')
    # ### end Alembic commands ###
