[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:.*StarletteDeprecationWarning.*
    ignore:.*Using `httpx` with `starlette.testclient` is deprecated.*
    ignore:.*enable_cleanup_closed.*:DeprecationWarning

