"""initial schema

Revision ID: 3113533826e3
Revises: 'None'
Create Date: 2026-08-02 12:57:41.815728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3113533826e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("level IN ('DEBUG','INFO','WARNING','ERROR','CRITICAL')", name='chk_bot_log_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bot_logs_level', 'bot_logs', ['level'], unique=False)
    op.create_index('idx_bot_logs_module', 'bot_logs', ['module'], unique=False)
    op.create_table('bot_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('idx_bot_settings_category', 'bot_settings', ['category'], unique=False)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_exchanges_status', 'exchanges', ['status'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('risk_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('max_open_trade', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_risk_profiles_is_active', 'risk_profiles', ['is_active'], unique=False)
    op.create_table('signal_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_signal_providers_is_active', 'signal_providers', ['is_active'], unique=False)
    op.create_index('idx_signal_providers_type', 'signal_providers', ['type'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uk_strategies_name_version')
    )
    op.create_index('idx_strategies_is_active', 'strategies', ['is_active'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('base_asset', sa.Text(), nullable=False),
    sa.Column('quote_asset', sa.Text(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('step_size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('qty_precision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'symbol', name='uk_instruments_exchange_symbol')
    )
    op.create_index('idx_instruments_is_active', 'instruments', ['is_active'], unique=False)
    op.create_index('idx_instruments_symbol', 'instruments', ['symbol'], unique=False)
    op.create_table('trading_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), server_default='MAINNET', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_accounts_exchange_id', 'trading_accounts', ['exchange_id'], unique=False)
    op.create_index('idx_trading_accounts_is_active', 'trading_accounts', ['is_active'], unique=False)
    op.create_table('daily_risk_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('risk_profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date', name='uk_daily_risk_account_date')
    )
    op.create_index('idx_daily_risk_account_id', 'daily_risk_config', ['account_id'], unique=False)
    op.create_index('idx_daily_risk_date', 'daily_risk_config', ['date'], unique=False)
    op.create_index('idx_daily_risk_profile_id', 'daily_risk_config', ['risk_profile_id'], unique=False)
    op.create_table('trading_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.Text(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('encrypted_secret_key', sa.Text(), nullable=False),
    sa.Column('encrypted_passphrase', sa.Text(), nullable=True),
    sa.Column('key_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trading_credentials_account_id', 'trading_credentials', ['account_id'], unique=False)
    op.create_index('idx_trading_credentials_is_active', 'trading_credentials', ['is_active'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.Text(), nullable=True),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('entry_min', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('entry_max', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tp1_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp2_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp3_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=True),
    sa.Column('parsed_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='RECEIVED', nullable=False),
    sa.Column('confirmation_status', sa.Text(), server_default='NOT_REQUIRED', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("confirmation_status IN ('NOT_REQUIRED','PENDING','APPROVED','REJECTED')", name='chk_signal_confirm'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='chk_signal_side'),
    sa.CheckConstraint("status IN ('RECEIVED','EXECUTED','REJECTED','CANCELLED','EXPIRED')", name='chk_signal_status'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['signal_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_instrument_id', 'trading_signals', ['instrument_id'], unique=False)
    op.create_index('idx_signal_provider_id', 'trading_signals', ['provider_id'], unique=False)
    op.create_index('idx_signal_status', 'trading_signals', ['status'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_enabled', 'watchlist', ['enabled'], unique=False)
    op.create_index('idx_watchlist_instrument_id', 'watchlist', ['instrument_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='WAITING_ENTRY', nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('avg_entry_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('tp1_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp2_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp3_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('margin_mode', sa.Text(), server_default='ISOLATED', nullable=False),
    sa.Column('position_size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('remaining_qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("margin_mode IN ('ISOLATED','CROSSED')", name='chk_trade_margin'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='chk_trade_side'),
    sa.CheckConstraint("status IN ('WAITING_ENTRY','OPEN','PARTIAL','CLOSED','CANCELLED')", name='chk_trade_status'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_account_id', 'trades', ['account_id'], unique=False)
    op.create_index('idx_trade_instrument_id', 'trades', ['instrument_id'], unique=False)
    op.create_index('idx_trade_signal_id', 'trades', ['signal_id'], unique=False)
    op.create_index('idx_trade_status', 'trades', ['status'], unique=False)
    op.create_index('idx_trade_strategy_id', 'trades', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('exchange_order_id', sa.Text(), nullable=True),
    sa.Column('client_order_id', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('close_position', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('time_in_force', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='NEW', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("order_type IN ('MARKET','LIMIT','STOP_MARKET','TAKE_PROFIT_MARKET','TRAILING_STOP_MARKET')", name='chk_order_type'),
    sa.CheckConstraint("purpose IN ('ENTRY','TP1','TP2','TP3','SL','BEP_SL','TRAILING_SL','MANUAL_CLOSE')", name='chk_order_purpose'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='chk_order_side'),
    sa.CheckConstraint("status IN ('NEW','PARTIALLY_FILLED','FILLED','CANCELED','EXPIRED','REJECTED')", name='chk_order_status'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id'),
    sa.UniqueConstraint('exchange_order_id')
    )
    op.create_index('idx_orders_exchange_order_id', 'orders', ['exchange_order_id'], unique=False)
    op.create_index('idx_orders_purpose', 'orders', ['purpose'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_trade', 'orders', ['trade_id'], unique=False)
    op.create_table('trade_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("event_type IN ('ENTRY','TP1','TP2','TP3','SL','SL_MOVED_TO_BEP','SL_MOVED_TO_TP1','TRAILING_ENABLED','MANUAL_CLOSE','FORCE_CLOSE','FAILSAFE_SYNC','FUNDING')", name='chk_event_type'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trade_events_trade', 'trade_events', ['trade_id'], unique=False)
    op.create_table('trade_risk',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('daily_risk_id', sa.Integer(), nullable=False),
    sa.Column('entry', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_distance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['daily_risk_id'], ['daily_risk_config.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_trade_risk_daily_risk_id', 'trade_risk', ['daily_risk_id'], unique=False)
    op.create_table('trade_summary',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('funding', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('roi', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rr', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('close_reason', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("result IN ('WIN','LOSS','BREAKEVEN')", name='chk_summary_result'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index('idx_trade_summary_result', 'trade_summary', ['result'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('commission_asset', sa.Text(), server_default='USDT', nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), server_default='0', nullable=False),
    sa.Column('is_maker', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_executions_order_id', 'executions', ['order_id'], unique=False)
    op.create_index('idx_executions_trade_id', 'executions', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_executions_trade_id', table_name='executions')
    op.drop_index('idx_executions_order_id', table_name='executions')
    op.drop_table('executions')
    op.drop_index('idx_trade_summary_result', table_name='trade_summary')
    op.drop_table('trade_summary')
    op.drop_index('idx_trade_risk_daily_risk_id', table_name='trade_risk')
    op.drop_table('trade_risk')
    op.drop_index('idx_trade_events_trade', table_name='trade_events')
    op.drop_table('trade_events')
    op.drop_index('idx_orders_trade', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_purpose', table_name='orders')
    op.drop_index('idx_orders_exchange_order_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_trade_strategy_id', table_name='trades')
    op.drop_index('idx_trade_status', table_name='trades')
    op.drop_index('idx_trade_signal_id', table_name='trades')
    op.drop_index('idx_trade_instrument_id', table_name='trades')
    op.drop_index('idx_trade_account_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_watchlist_instrument_id', table_name='watchlist')
    op.drop_index('idx_watchlist_enabled', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index('idx_signal_status', table_name='trading_signals')
    op.drop_index('idx_signal_provider_id', table_name='trading_signals')
    op.drop_index('idx_signal_instrument_id', table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index('idx_trading_credentials_is_active', table_name='trading_credentials')
    op.drop_index('idx_trading_credentials_account_id', table_name='trading_credentials')
    op.drop_table('trading_credentials')
    op.drop_index('idx_daily_risk_profile_id', table_name='daily_risk_config')
    op.drop_index('idx_daily_risk_date', table_name='daily_risk_config')
    op.drop_index('idx_daily_risk_account_id', table_name='daily_risk_config')
    op.drop_table('daily_risk_config')
    op.drop_index('idx_trading_accounts_is_active', table_name='trading_accounts')
    op.drop_index('idx_trading_accounts_exchange_id', table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index('idx_instruments_symbol', table_name='instruments')
    op.drop_index('idx_instruments_is_active', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('idx_strategies_is_active', table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('idx_signal_providers_type', table_name='signal_providers')
    op.drop_index('idx_signal_providers_is_active', table_name='signal_providers')
    op.drop_table('signal_providers')
    op.drop_index('idx_risk_profiles_is_active', table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index('idx_exchanges_status', table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index('idx_bot_settings_category', table_name='bot_settings')
    op.drop_table('bot_settings')
    op.drop_index('idx_bot_logs_module', table_name='bot_logs')
    op.drop_index('idx_bot_logs_level', table_name='bot_logs')
    op.drop_table('bot_logs')
    # ### end Alembic commands ###
